### ISSUE TITLE
Update the routes.py file to contain Flask service routes

### ISSUE THREAD

**Issue by Awesalot** [CSCI-GA-2820-FA22-003/promotions#17]
**As a** Developer
**I need** a route file for Flask service routes  
**So that** the team can add routes and edit responses in a modular fashion

**Details & Assumptions:** 
* The response will be in JSON format
* The routes will have functionalities independent of each other 

**Acceptance Criteria:**

```gherkin
Given the server is available
When I access a route URL
Then I get a response corresponding to the Flask service route
```

**Comment by Aman-Chopra** [comment]
We can remove the brackets from the issue for the formatting to be consistent with other issues

Given the service is available
When I access a route URL
Then I get a response corresponding to the Flask service route
