### ISSUE TITLE
Add a new Action endpoint to Activate or Deactivate a Promotion

### ISSUE THREAD

**Issue by adwalvekar** [CSCI-GA-2820-FA22-003/promotions#18]
**As a** Promotions Manager
**I need** to be able to activate or deactivate a specific promotion
**So that** I can control the visibility and status of the promotion

**Details & Assumptions:** 
* The base URL would be `/promotions/{id}/activate`
* The HTTP method should be PUT or DELETE to activate or deactivate a promotion respectively.

**Acceptance Criteria:**

```gherkin
Given the service is available
When an error occurs while hitting the endpoint
Then a proper HTTP Status Code depicting the type of error should be returned
When I call the API `PUT /promotions/{id}/activate` with the HTTP PUT method
Then the status of the specific promotion should change to activated 
When I call the API `DELETE /promotions/{id}/activate` with the HTTP DELETE method
Then the status of the specific promotion should change to deactivated 
```

**Comment by Black-Caesaris** [comment]
Editing the details of this specific story as per latest requirements from the Assignment. Updating the scope of this story to take care of adding a new action endpoint for activating a promotion.
